//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentScope_Capstone_2021_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentReview
    {
        public int Id { get; set; }
        public string AgentId { get; set; }
        public string ReviewerId { get; set; }
        public short Rating { get; set; }
        public string BodyText { get; set; }
        public System.DateTime DateOfReview { get; set; }
    
        public virtual ReviewerAccount ReviewerAccount { get; set; }
        public virtual AgentAccount AgentAccount { get; set; }
    }
}
